Update electron-compiler.yml

diff --git a/.github/workflows/electron-compiler.yml b/.github/workflows/electron-compiler.yml
--- a/.github/workflows/electron-compiler.yml
+++ b/.github/workflows/electron-compiler.yml
@@ -11,7 +11,7 @@ jobs:
 
     strategy:
       matrix:
-        os: [windows-2016, ubuntu-18.04]
+        os: [windows-latest, ubuntu-18.04]
 
     steps:
       - name: Context
@@ -34,15 +34,25 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Cleanup artifacts
+        if: matrix.os != 'windows-latest'
         run: |
-          npx rimraf "dist/!(*.exe|*.deb|*.AppImage|*.dmg)"
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          mkdir artifacts
+          mv "dist/(*.exe,*.deb,*.AppImage,*.dmg)" artifacts || true
+      - name: Cleanup artifacts Win
+        if: matrix.os == 'windows-latest'
+        run: |
+          mkdir artifacts
+          mv dist/*.exe artifacts
+#       - name: Cleanup artifacts
+#         run: |
+#           npx rimraf "dist/!(*.exe|*.deb|*.AppImage|*.dmg)"
+#         env:
+#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Upload artifacts
         uses: actions/upload-artifact@v1
         with:
           name: ${{ matrix.os }}
-          path: dist
+          path: artifacts
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Release
